ethercrab-rs/ethercrab

.circleci/config.yml, CHANGELOG.md, Cargo.toml, benches/pdu_loop.rs, src/command.rs, src/internals.rs, src/lib.rs, src/pdu_loop/mod.rs, src/pdu_loop/pdu_rx.rs, src/std.rs
This is the most pure/basic possible benchmark of the PDU loop. It:
1. Prepares a `FPWR` frame with 8 bytes of payload data (32 bytes total) and marks it as sendable
2. Writes an Ethernet II packet containing the EtherCAT frame into a buffer
3. Passes the buffer to `receive_frame` which parses the data back out of the buffer
This test doesn't include any networking (not even loopback) because I'm on Windows so it's more a theoretical benchmark to check for regressions in the code than a real-world representation. On my Windows 11 (🤮) Ryzen 9 5950X system I get:
```
pdu-loop/elements       time:   [256.58 ns 257.65 ns 259.05 ns]
thrpt:  [3.8603 Melem/s 3.8812 Melem/s 3.8974 Melem/s]
pdu-loop/payload bytes  time:   [259.66 ns 261.35 ns 263.59 ns]
thrpt:  [28.944 MiB/s 29.193 MiB/s 29.382 …
```
=> Benchmark PDU loop

.circleci/config.yml, CHANGELOG.md, README.md, rust-toolchain.toml, src/lib.rs, src/pdu_loop/storage.rs
We're nightly free!
MSRV is 1.68 to use `core::pin::pin!`
=> Add workarounds so EtherCrab works on stable Rust

CHANGELOG.md, README.md, examples/akd.rs, examples/dc.rs, examples/ec400.rs, examples/ek1100.rs, examples/multiple-groups.rs, src/client.rs, src/client_config.rs, src/lib.rs
Adds a `ClientConfig` field to `Client::new()` to allow configuration of various behaviours. Currently only supports DC static sync iteration count.
Closes #15
=> Support configuring DC sync iterations

Cargo.toml, README.md, examples/akd.rs, examples/dc.rs, examples/ec400.rs, examples/ek1100.rs, examples/multiple-groups.rs, src/ds402.rs, src/lib.rs
- Migrate to `tokio` so we can cleanly spawn the TX/RX task in (potentially) another thread
- Clean up a lot of the code and comments to hopefully make it easier to follow along
This makes the examples more reliable too. In my testing, I'm no longer seeing `TX/RX: Timeout` errors spring up due to moving the TX/RX task into a multi-threaded executor.
=> Clean up examples and migrate them to `tokio`

CHANGELOG.md, README.md, examples/akd.rs, examples/dc.rs, examples/ec400.rs, examples/ek1100.rs, examples/multiple-groups.rs, examples/performance.rs, src/client.rs, src/lib.rs, src/slave_group/configurator.rs, src/slave_group/container.rs, src/slave_group/mod.rs, src/slave_group/slave_storage.rs
Instead of requiring the programmer to remember to `push` the slave device onto the current group, instead a reference to the desired group is returned from the closure, letting EtherCrab handle putting the slave in the right place.
E.g. `groups.slow_outputs.push(slave)` becomes `Ok(groups.slow_outputs.as_mut())`
Old API:
```rust
let groups = client
.init::<MAX_SLAVES, _>(Groups::default(), |groups, slave| {
match slave.name.as_str() {
"EL2889" | "EK1100" => groups.slow_outputs.push(slave),
"EL2828" => groups.fast_outputs.push(slave),
_ => Err(Error::UnknownSlave),
}
})
.await
.expect("Init");
```
New API:
```rust
let groups = client
.init::<MAX_SLAVES, _>(Groups::default(), |groups, slave| {
match slave.name.as_str() {
"EL2889" | "EK1100" => Ok(groups.slow_outputs.as_mut()),
"EL2828" => …
```
=> Refactor group initialisation

src/eeprom/types.rs, src/register.rs, src/slave/mod.rs, src/slave/ports.rs, src/slave_group/configurator.rs, src/slave_group/mod.rs, src/slave_group/slave_storage.rs
Closes #41 
This was a regression caused by the introduction of the internal `SlaveStorage` container - it was writing the slave device into the wrong piece of memory, meaning the retrieval of that slave's info would return a struct with all zeroes. This caused the error seen in #41 as it was sending an address of `0x0000` instead of `0x1000` (which the slave device is configured to.
=> Fix slave storage issues

.circleci/config.yml, Cargo.toml, src/lib.rs, src/pdu_loop/pdu_tx.rs, src/slave_group/mod.rs
Also fixes usage of `Box` in no_std so this crate should now compile for no_std targets. Note though that it still requires `alloc` to be present.
I'm hoping to redesign the API a bit to remove the requirement on `Box<dyn ...>` which would mean no dynamic alloc is required by EtherCrab at all.
Closes #56
=> Fix smoltcp feature

Cargo.toml, src/slave_group/configurator.rs, src/timer_factory.rs
I haven't included it in this PR because it times out but I ran a MIRI pass over a replay test and it didn't throw up any errors so I _think_ this is safe?
=> Make init future `Send`-able

src/register.rs, src/slave/mod.rs, src/slave/ports.rs, src/slave/types.rs
The slave info debug line now prints more info than just address and name:
```
Slave 0x1000 name EK1100 vendor: 0x00000002, product 0x044c2c52, rev 1179648, serial 0, DC: yes (64 bit), ports [ open open closed closed ]
```
this adds a bit more data before any other potential failures.
=> Add `Display` impls to print out more slave details

src/dc.rs, src/slave/ports.rs, tests/README.md
I could reproduce the error in #63 using the provided Wireshark captures, however for some mysterious reason every single module I plug into my EK1100 shows up as `DC: yes` so I'm unable to test this fix. 
Closes #63
=> Ignore non-DC slaves when configuring DC

examples/ec400.rs, src/ds402.rs
This is IMO the last blocker to a new release. I toyed with the idea of removing it or feature flagging it, but I think leaving it in with a mention that it's experimental is ok.
=> Mention that the DS402 module is experimental

CHANGELOG.md, src/slave/mod.rs
This was already present on `Slave` but needs to be usable with `SlaveRef` too.
=> Add `SlaveRef::identity`

CHANGELOG.md, src/fmt.rs, src/slave_group/iterator.rs, src/slave_group/mod.rs
This trait was `#[doc(hidden)]` before.
This PR also changes `SlaveGroup::iter` behaviour to panic on reborrow instead of silently completing early.
=> Expose method to get a single slave device

CHANGELOG.md, examples/discover.rs, src/dc.rs, src/fmt.rs, src/slave/mod.rs, src/slave/ports.rs
This was a nice rabbit hole as the already existing topology propagation times weren't being calculated correctly either. I think.
Cross topo, e.g. with EK1122 is supported now, and should have the correct propagation times.
=> Support "cross" topologies

src/client.rs, src/pdu_loop/frame_element/received_frame.rs
`master`:
```
111056     112   50560  161728   277c0 ethercrab-stm32-embassy
```
This PR:
```
108580     112   50560  159252   26e14 ethercrab-stm32-embassy
```
=> Reduce binary size a bit more

src/dc.rs, src/eeprom/reader.rs, src/slave/configuration.rs, src/slave/eeprom.rs, src/slave/mod.rs, src/slave/slave_client.rs
Split `SlaveClient` from `SlaveRef`. This removes a generic, so code size is reduced from less monomorphisation. 
Also some EEPROM code size optimisations.
`master`
```
96012     112   50560  146684   23cfc ethercrab-stm32-embassy
```
This PR
```
90604     112   50560  141276   227dc ethercrab-stm32-embassy
```
=> Reintroduce `SlaveClient`, size-optimise EEPROM

.circleci/config.yml, CHANGELOG.md, benches/pdu_loop.rs, examples/embassy-stm32/src/main.rs, src/client.rs, src/pdu_loop/frame_element/created_frame.rs, src/pdu_loop/frame_element/mod.rs, src/pdu_loop/frame_element/receiving_frame.rs, src/pdu_loop/frame_element/sendable_frame.rs, src/pdu_loop/mod.rs, src/pdu_loop/pdu_rx.rs, src/pdu_loop/storage.rs, src/slave/ports.rs, src/std/linux/mod.rs, src/std/not_linux.rs, tests/util.rs
This should allow frame send retry attempts so EtherCrab is more resilient against temporary (within `Timeouts::pdu`) network outages.
=> Release in-flight frames when the send fails

CHANGELOG.md, benches/pdu_loop.rs, src/client.rs, src/client_config.rs, src/lib.rs, src/pdu_loop/mod.rs, src/std/linux/mod.rs
This builds on #101 and makes the retry behaviour much more robust. In my local testing, I can unplug the EtherCAT network cable and replug it and the slaves (EL2828, EL2889 in my case) pick the PDI back up again. 
According to <https://infosys.beckhoff.com/english.php?content=../content/1033/el34x3/1036979339.html&id=>, the slaves won't fall out of OP when no PDI is received but their watchdogs will trigger, causing outputs to be turned off for safety.
=> Allow configuration of retry behaviour for timed out PDUs

CHANGELOG.md, Cargo.toml, README.md, src/coe/abort_code.rs, src/command.rs, src/error.rs, src/lib.rs, src/pdu_loop/frame_element/sendable_frame.rs, src/slave_state.rs
Currently only implemented for `ethercrab::error::Error` as this is all I need for now but is easy enough to add to more stuff in the future.
=> Add `serde` support to `Error`

CHANGELOG.md, src/pdu_loop/mod.rs
These shouldn't have been `pub` in the first place. Oops!
=> Un-pub internal-only methods on `PduLoop`

src/command.rs
It was missing a closing paren on some branches
=> Fix `Command` `Display` output

CHANGELOG.md, src/std/linux/mod.rs
This PR relaxes the `'static` bound down to a specified lifetime. This can remain static for any `static PduStorage`s so shouldn't be a breaking change, but now additionally allows the use of scoped threads or similar.
=> Relax std task storage lifetime

CHANGELOG.md, src/slave/mod.rs
Adds the ability to get the propagation delay of a device to use for diagnostics, logging, etc.
=> Expose device propagation delay via a method

src/pdu_loop/frame_element/receiving_frame.rs
This makes it easier to match up Wireshark traces to error logs.
=> Print frame index in hex too

CHANGELOG.md, Cargo.toml, examples/embassy-stm32/Cargo.toml, examples/embassy-stm32/rust-toolchain.toml, examples/embassy-stm32/src/main.rs, src/al_control.rs, src/std/linux/mod.rs, src/std/linux/raw_socket.rs
Just pottering around. Saves a few KB for `no_std`:
```bash
cd examples/embassy-stm32
cargo size --release
```
```
Baseline (master branch)
91348     112   52784  144244   23374 ethercrab-stm32-embassy
This PR
89072     112   52784  141968   22a90 ethercrab-stm32-embassy
```
=> Package upgrades, update Embassy example

.circleci/config.yml, CHANGELOG.md, src/pdu_loop/frame_element/mod.rs, src/pdu_loop/frame_element/received_frame.rs, src/pdu_loop/frame_element/receiving_frame.rs, src/pdu_loop/mod.rs, src/pdu_loop/pdu_rx.rs, src/pdu_loop/storage.rs
Prior to this PR, if the frame slot at the `N + 1`th index was still occupied, an error would occur. Now, the PDU loop storage code will loop through the entire slot space up to 2 times looking for a free slot to use.
This mitigates situations where a frame from a previous cycle or another thread is still marked as in use (e.g. because its payload data is still held). Now, the PDU loop will skip over that slot and go looking for the next free one. Not a total fix, but much improved when testing with 11 threads - one tx/rx and 10 others running tasks simultaneously.
Also adds a bunch of logging.
=> Improve behaviour when frames are still in flight

CHANGELOG.md, src/mailbox.rs, src/slave/mod.rs
The spec seems a little vague on what to actually do with the counter, and as far as I can read into SOEM's rather dence C it doesn't seem to check the value either. Based on this, I've removed the check in EtherCrab.
Closes #128
=> No longer check mailbox counter

CHANGELOG.md, Justfile, README.md, examples/akd.rs, examples/dc.rs, examples/ec400.rs, examples/ek1100.rs, examples/embassy-stm32/src/main.rs, examples/jitter.rs, examples/multiple-groups.rs, examples/performance.rs, src/ds402.rs, src/lib.rs, src/slave/pdi.rs, tests/replay-ek1100-el2828-el2889.rs
Breaking change. Sorry about that! The fix is a rename and the odd `mut` here and there so hopefully not too bad.
Some fixes and additions for `SlaveRef` methods:
- Adds `io_raw_mut` and `outputs_mut`. `io_raw` and `outputs` now only return immutable references.
- Fixes a soundness bug where multiple calls to `io_raw` would result in multiple mutable references being held to the same data.
=> Shuffle `SlaveRef` methods around

CHANGELOG.md, src/al_status_code.rs
As title :) just removes the bogus `I` from the end.
=> Fix `AlStatusCode::ApplicationControllerAvailableI` typo

CHANGELOG.md, src/error.rs, src/pdu_loop/pdu_rx.rs
The field in the EtherCAT frame is a `u8` so it makes no sense for the reported error to be a `usize`.
=> Change `PduError::InvalidIndex` to hold a `u8`, not a `usize`

CHANGELOG.md, src/client.rs, src/dc.rs, src/eeprom/device_reader.rs, src/error.rs, src/pdu_loop/frame_element/received_frame.rs, src/pdu_loop/mod.rs, src/slave/configuration.rs, src/slave/mod.rs, src/slave/slave_client.rs
It's not particularly useful for troubleshooting, and doesn't really provide anything that a normal error log and a Wireshark capture can't, beyond adding bloat the resulting binary which is important for embedded systems.
=> Remove `context` from `Error::WorkingCounter`

Cargo.toml
- Use newer optional dependency syntax
- Remove `nom` as it's no longer used anywhere in the code
=> Tweak dependencies

src/client.rs, src/command/reads.rs, src/command/writes.rs, src/eeprom/device_reader.rs, src/pdu_loop/mod.rs, src/slave/mod.rs, src/slave_group/mod.rs, src/timer_factory.rs
Slightly cleaner code around timing out futures.
Also reduces binary size which was the primary motivator for this PR.
=> Add a trait for cleaner timeouts

CHANGELOG.md, Cargo.toml, examples/embassy-stm32/Cargo.toml, examples/embassy-stm32/src/main.rs
`embassy` recently released stable versions of their crates, so we can remove the nightly patches.
The only ethercrab-specific change is a bump of `embassy-time` to 0.3.0.
=> Upgrade Embassy example to stable crate versions

src/slave/configuration.rs
Where's your fancy type system now, huh
=> Fix typo in mailbox sync manager configuration

Cargo.toml, ethercrab-wire-derive/src/generate_enum.rs, ethercrab-wire-derive/src/help.rs, ethercrab-wire-derive/src/parse_enum.rs, ethercrab-wire-derive/ui/enum-isize.rs, ethercrab-wire-derive/ui/enum-isize.stderr, ethercrab-wire-derive/ui/enum-usize.rs, ethercrab-wire-derive/ui/enum-usize.stderr, ethercrab-wire/tests/signed-enums.rs
- Add support for `i8`, `i16`, `i32` and `i64` enum discriminants.
- Add support for `u64` enum discriminant
- Explicitly mention that `isize` and `usize` are not supported as they can change width on different platforms.
=> Support `i*` types for enum discriminants

ethercrab-wire-derive/src/generate_enum.rs, ethercrab-wire-derive/src/generate_struct.rs, ethercrab-wire/src/impls.rs, ethercrab-wire/tests/signed-enums.rs
This change makes for more expected behaviour when packing into existing non-zero buffers. It will be slightly slower and increase code size but is the safer way to go.
`ptr::write_bytes` is used instead of `slice::fill` as it does the same thing with a little less code according to [Godbolt](https://godbolt.org/z/4G888xsKb).
=> Zero out packing buffers before use

Cargo.toml
I've been pulling my hair out wondering why the logging wasn't working properly! The `std` feature should enable `log` by default.
Regression caused in #150.
=> Fix logging when `std` feature is enabled

ethercrab-wire/src/impls.rs
An oversight on my part. Oops!
=> Support decoding of `f32` and `f64`

CHANGELOG.md, src/pdu_data.rs
Note that `f64`s cannot currently be passed to `sdo_write` as it only supports 4 byte expedited transfers currently.
=> Support reading/writing `f32`, `f64` and `bool`

ethercrab-wire/src/impls.rs
The EtherCAT spec ETG1000.6 5.2.2 Encoding of a Boolean value states that `true` is `0xff` and false is `0x00`. This PR fixes the prior assumed behaviour of `0x01`/`0x00` which is incorrect for `true` values.
#167 includes this fix for 0.3.x releases.
=> Correct bool encoding/decoding

src/internals.rs, src/pdu_loop/frame_header.rs, src/pdu_loop/mod.rs, src/pdu_loop/pdu_header.rs, src/pdu_loop/pdu_rx.rs, tests/util.rs
This is some precursory work to support multiple PDUs per Ethernet frame.
The EtherCAT header is now split from the PDU frame header, more easily allowing for multiple PDU frames in the future.
=> Split frame parsing up

CHANGELOG.md, Cargo.toml, src/std/windows.rs
This will merge into `master`, which is the upcoming 0.4 release.
A future PR will backport this to 0.3.x.
=> Relax Windows `'static` TX/RX lifetime, fix some unwraps

Cargo.toml, src/pdu_loop/mod.rs, src/slave/mod.rs
`futures_lite` does the same thing and is also used by `smol`, so this shortens the dependency tree just a tiny bit
=> Remove `embassy-futures` and last uses of it

Cargo.toml, NOTES.md, examples/dc.rs, src/std/unix/mod.rs
Also improves reliability of `smol`-based TX/RX task by spinning if a received frame's future isn't registered yet.
The added code tries to establish a reasonably close synchronisation between the OS and EtherCat system clock using a PI loop.
This isn't hugely useful because we need to figure out when a cycle starts, not what the current system time is, but I'll add it anyway because it might be useful down the line. If for nothing more than the PI loop boilerplate.
=> Add some more DC sync experiment

src/command/writes.rs, src/slave_group/mod.rs
Halves the number of frames sent/received when using distributed clocks by merging two PDUs into one Ethernet frame.
=> Send DC sync `FRMW` in same frame as process data `LRW`

.gitignore, CHANGELOG.md, Cargo.toml, examples/dc.rs, src/slave_group/mod.rs
This PR updates the `dc` example to correctly start distributed clock SYNC0 cycles at a point in the future so that the MainDevice can sync to the DC System Time and maintain a constant offset.
The example uses an offset of 50% on a 5ms cycle time, i.e. the process data is sent 2.5ms after the SYNC0 pulse. This has been checked against a LAN9252 dev board, looking at the SYNC0 and IRQ pins on an oscilloscope.
MainDevice jitter is also compensated for by adding a variable delay to the next process data cycle. This produces very consistent MainDevice cycle ticks - we're down into microseconds of jitter on my test system.
=> Correctly configure first SYNC0 pulse

CHANGELOG.md, examples/akd.rs, examples/dump-eeprom.rs, examples/ec400.rs, examples/io-uring.rs, examples/multiple-groups.rs, examples/performance.rs, examples/smol-io-uring.rs, src/lib.rs, src/slave_group/iterator.rs, src/slave_group/mod.rs, tests/replay-ek1100-el2828-el2889-no-reborrow.rs, tests/replay-ek1100-el2828-el2889.rs, tests/replay-ek1914-el3004-mailbox.rs, tests/replay-ek1914-no-complete-access.rs, tests/replay-ek1914-segmented-upload.rs
Turns out this trait isn't really necessary as long as we don't mind a little bit of "manual monomorphisation" for `GroupSlaveIterator`. No user visible changes. Simplified internals.
=> Remove `SlaveGroupState` trait

examples/dc.rs, src/slave_group/mod.rs
It also configures `SYNC1` now :)
=> Rename `configure_dc_sync0` to `configure_dc_sync`

examples/dc-lan9252-groups.rs, examples/dc.rs
Silly logic mistake by yours truly. The LAN9252 was never being enabled for SYNC0, which meant it always errored out with "invalid DC sync configuration".
=> Get `dc` example working on LAN9252 devboards again

Cargo.toml, examples/c5-e.rs, src/ds402.rs
Example was tested with 
- [C5-E-1-21](https://en.nanotec.com/products/2644-c5-e-1-21-motor-controller-drive-for-ethercat-or-usb) drive
- [AS5918M2804-E](https://en.nanotec.com/products/611-as5918m2804-e) motor
=> Add example for Nanotec C5-E stepper controller

CHANGELOG.md, src/client.rs, src/client_config.rs, src/pdu_loop/frame_element/created_frame.rs, src/pdu_loop/frame_element/mod.rs, src/pdu_loop/frame_element/receiving_frame.rs, src/pdu_loop/mod.rs, src/pdu_loop/storage.rs, src/timer_factory.rs
As opposed to using a `for` loop. This change results in a slight reduction in binary size which was the goal of the PR.
Master:
```
99472     112   57800  157384   266c8 ethercrab-stm32-embassy
```
This commit:
```
99316     112   57800  157228   2662c ethercrab-stm32-embassy
```
As well as a ~10% improvement in throughput in the `pdu_loop` benchmark as a nice bonus.
=> Handle frame timeout logic in response future

src/client.rs, src/command/reads.rs, src/command/writes.rs, src/pdu_loop/frame_element/created_frame.rs, src/pdu_loop/frame_element/frame_box.rs, src/pdu_loop/frame_element/mod.rs, src/pdu_loop/frame_element/received_frame.rs, src/pdu_loop/frame_element/receiving_frame.rs, src/pdu_loop/frame_element/sendable_frame.rs, src/pdu_loop/mod.rs, src/pdu_loop/pdu_rx.rs, src/pdu_loop/pdu_tx.rs, src/pdu_loop/storage.rs, src/slave/mod.rs, src/slave_group/mod.rs
`PduMarker` became unnecessary and was removed, which is a huge relief as that whole set of code was a horrible hack I was never happy with. Received EtherCAT frames are now matched up to their backing data by parsing out the first PDU index in the frame and doing a linear search over the (up to) 256 frame slots. Benchmark performance improved by ~4% and embedded binary size reduced a lot too:
`master`:
```
96576     112   57800  154488   25b78 ethercrab-stm32-embassy
```
This PR:
```
92216     112   57288  149616   24870 ethercrab-stm32-embassy
```
=> Massively simplify frame/PDU code

Cargo.toml, benches/pdu_loop.rs, src/pdu_loop/frame_element/created_frame.rs, src/pdu_loop/frame_element/mod.rs
- Remove unused field from `FrameElement`, saving a few bytes in the resulting binary
- Change `pdu_loop` benchmark to measure Ethernet frame throughput. Previously this was only measuring payload throughput, but IMO the total throughput is what matters when considering performance for e.g. EtherCAT G (1Gbit)
Benchmarking on an M1 MacBook Air sees 73MiB/sec or ~600mbit. Still a ways to go if somebody wants to saturate gigabit Ethernet, but decently close.
=> More housekeeping

.circleci/config.yml, ethercrab-wire-derive/src/generate_struct.rs, ethercrab-wire/src/impls.rs, src/ds402.rs, src/eeprom/mod.rs, src/eeprom/types.rs, src/lib.rs, src/pdu_loop/frame_element/received_frame.rs, src/pdu_loop/mod.rs, src/pdu_loop/pdu_rx.rs, src/slave/eeprom.rs, src/slave/mod.rs, src/slave_group/mod.rs, src/std/io_uring.rs, src/std/unix/mod.rs
Discovered and fixed by temporarily adding `#![deny(clippy::indexing_slicing)]` (https://rust-lang.github.io/rust-clippy/master/index.html#/indexing_slicing). Allows more graceful error handling.
Slight binary size reduction:
`master`
```
89768     112   57288  147168   23ee0 ethercrab-stm32-embassy
```
This branch:
```
88800     112   57288  146200   23b18 ethercrab-stm32-embassy
```
Performance is unchanged.
Also added a few general clippy fixes to this PR.
=> Remove a bunch of panicking indexing operations

NOTES.md, ethercrab-wire-derive/benches/derive-large.rs
Previously, this benchmark was only running a subset of the defined types due to a copy paste error.
=> Actually benchmark large struct ser/de

Cargo.toml, src/error.rs, src/ethernet.rs, src/internals.rs, src/lib.rs, src/pdu_loop/frame_element/frame_box.rs, src/pdu_loop/frame_element/mod.rs, src/pdu_loop/frame_element/receiving_frame.rs, src/pdu_loop/frame_element/sendable_frame.rs, src/pdu_loop/mod.rs, src/pdu_loop/pdu_rx.rs, src/pdu_loop/storage.rs, src/std/unix/bpf.rs, src/std/unix/linux.rs, src/std/windows.rs, tests/util.rs
I really like `smoltcp`, but it turns out I'm only using two types out of it, so it doesn't make much sense to include the whole dependency. This also frees up #162 to be merged, which is a nice bonus :)
=> Remove `smoltcp`, copy and strip down SmolTCP ethernet types

CHANGELOG.md, Cargo.toml, ethercrab-wire-derive/CHANGELOG.md, ethercrab-wire-derive/Cargo.toml, ethercrab-wire-derive/src/parse_enum.rs, ethercrab-wire-derive/src/parse_struct.rs, ethercrab-wire/CHANGELOG.md, ethercrab-wire/Cargo.toml, rust-toolchain.toml, src/timer_factory.rs
Mostly to support `collapse_debuginfo` in `embassy-time`.
=> Bump Rust MSRV to 1.79

CHANGELOG.md, Cargo.toml, src/subdevice_group/mod.rs
This was originally fixed by @jabratn in [this commit on their fork](https://github.com/ethercrab-rs/ethercrab/commit/8a24b009dca6fedf90a9d69efff346d955d1e464). I hope you don't mind me taking the fix! I've added the `Co-Authored-By` header to give due credit.
Tested on my EK1100 setup which panics on overflow when on `master`, but doesn't on this branch (but still calculates the offset correctly).
=> Fix overflowing subtraction when calculating DC cycle offset

CHANGELOG.md, src/eeprom/types.rs, src/subdevice/configuration.rs, src/subdevice/eeprom.rs
This PR also stops validating PDO ranges as I think I had that logic incorrect. For example, the EL2262 has a PDO mapping of 0x1701 which was outside the checked ranges, but is valid for a fixed set of mappings.
There's also some small refactoring around reading sub-items from the EEPROM which makes the code cleaner to read.
Closes #175
=> Support up to 64 PDO entries when reading from EEPROM

src/coe/services.rs, src/error.rs, src/subdevice/mod.rs
A customer is seeing an issue where a CoE request is sent with `counter = 1`, but is returned with `counter = 2`. The response seems otherwise valid, with the expected index/subindex, so I'm not sure what's going on. 
This PR stops checking the returned counter value, and instead does some extra validation on the index/subindex to be more confident the response is to the request we sent.
=> Don't check returned counter in CoE responses

CHANGELOG.md, examples/dc.rs, src/maindevice.rs, src/pdu_loop/frame_element/created_frame.rs, src/pdu_loop/frame_element/received_frame.rs, src/pdu_loop/mod.rs, src/pdu_loop/storage.rs, src/subdevice_group/mod.rs
This was previously done in chunks of 16 in #237 but that was a pretty arbitrary limitation. Now, the check frame is filled until nothing else will fit in it. At this point, another frame is sent if the group is large enough to need more than one.
=> Pack as many state changes as possible into check frame

src/std/unix/mod.rs
Discovered when trying to run ethercrab's `discover` example with dev profile on raspberry pi 3B+. 
Generally this prevents the overflow, but it still leaves the code vunerable to Y2k38 problem. Unfortunetally `libc` crate doesn't yet provide the option to use 64 bit version of `time_t` on 32 bit systems, hence I submit only this minimal change.  
Here's the full stacktrace for `discover` example:
```
thread 'main' panicked at src/std/unix/mod.rs:155:14:
attempt to multiply with overflow
stack backtrace:
0: rust_begin_unwind
at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:652:5
1: core::panicking::panic_fmt
at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/panicking.rs:72:14
2: core::panicking::panic_const::panic_const_mul_overflow
at …
```
=> Avoid overflow when calculating time on systems with 32-bit time_t

CHANGELOG.md, Cargo.toml, examples/ek1100.rs, examples/windows.rs, src/lib.rs, src/pdu_loop/mod.rs, src/pdu_loop/pdu_rx.rs, src/std/io_uring.rs, src/std/mod.rs, src/std/unix/mod.rs, src/std/windows.rs, tests/util.rs
=> Add a blocking Windows TX/RX function

CHANGELOG.md, src/maindevice.rs, src/pdu_loop/frame_element/created_frame.rs, src/pdu_loop/frame_element/frame_box.rs, src/pdu_loop/frame_element/mod.rs, src/pdu_loop/mod.rs, src/std/io_uring.rs, src/subdevice/configuration.rs, src/subdevice_group/mod.rs
This chunks a SubDevice group's PDI and sends it over multiple Ethernet/EtherCAT frames if the allocated storage is too small to send the whole PDI in one PDU.
TODO
=> Support PDIs longer than a single frame can hold

.circleci/config.yml, src/std/io_uring.rs, src/std/unix/mod.rs, src/std/windows.rs
The behaviour is the same, but now the code is easier to follow.
This should've been in #260, but I forgot to change it before merging.
=> Remove now-unused loops

examples/discover.rs, src/subdevice/mod.rs
I found that the device description for a Beckhoff EL1259 is 68B, just over the 64B limit presently.  Doubling the limit solves the issue.
=> Increase size limit for device descriptions to 128 bytes

CHANGELOG.md, ethercrab-wire/tests/irl.rs, ethercrab-wire/tests/signed-enums.rs, ethercrab-wire/tests/std.rs, examples/dc-lan9252-groups.rs, examples/dc.rs, examples/discover.rs, examples/ek1100.rs, examples/multiple-groups.rs, examples/release.rs, src/lib.rs, src/maindevice.rs, src/pdu_loop/frame_element/mod.rs, src/pdu_loop/mod.rs, src/pdu_loop/pdu_rx.rs, src/pdu_loop/pdu_tx.rs, src/pdu_loop/storage.rs, src/std/io_uring.rs, src/std/mod.rs, src/std/unix/mod.rs, src/std/windows.rs
TODO
- [-] ~Tests for both `release` and `release_all`~ very, very difficult to do replay tests with the current harness.
=> Add `release` and `release_all` methods

src/dc.rs, src/eeprom/types.rs, src/maindevice.rs, src/pdi.rs, src/register.rs, src/subdevice/configuration.rs, src/subdevice/eeprom.rs, src/subdevice/mod.rs, src/subdevice/pdi.rs, src/subdevice/ports.rs
Reduces Embassy example binary size from:
```
❯ cargo size -q --release
98444      80  110456  208980   33054 ethercrab-stm32-embassy
```
to:
```
❯ cargo size -q --release
96272      80  110456  206808   327d8 ethercrab-stm32-embassy
```
The example now compiles and works, so:
Closes #276
=> Reduce embedded example binary size a bit

CHANGELOG.md, Cargo.toml, examples/dump-eeprom.rs, src/internals.rs, src/subdevice/eeprom.rs, src/subdevice/mod.rs
Adds read and write methods for a SubDevice's EEPROM. For example, to dump the entire contents:
```rust
let eeprom_len = subdevice
.eeprom_size(&maindevice)
.await
.expect("Could not read EEPROM len");
log::info!("--> Device EEPROM is {} bytes long", eeprom_len);
let mut buf = vec![0u8; eeprom_len];
// Read entire EEPROM into buffer
subdevice.eeprom_read_raw(&maindevice, 0, &mut buf).await?;
```
Also removes some duplicated methods and replaces their "existence" with `Deref` and `DerefMut` impls.
=> Add EEPROM API, `Deref` and `DerefMut` impls to `SubDevice{Ref}`

CHANGELOG.md, src/subdevice/eeprom.rs, tests/replay-ek1100-el2828-el2889.rs
#288:
* Handle wrapping add in EEPROM address increment
* Add heuristic to stop searching through a pile of empty categories
=> Backport #288 to 0.5

CHANGELOG.md, src/eeprom/types.rs, src/subdevice/configuration.rs
The log in #290 shows `usage_type: Unknown` however the fields in `control.operation_mode` and `control.direction` are populated, so we can use them as a fallback to compute the SM type when the EEPROM data is incomplete.
This is another PR in a few like #291 that handle missing data in the EEPROM. Another reason to support ESI files as they seem to be the preferred way for manufacturers to configure their devices...
Closes #290
=> Fall back to other fields when computing SM type

src/dc.rs, src/eeprom/device_provider.rs
This does not upgrade to 2024, just fixes the "this will become an error in the future" warnings popped up currently.
=> Fix 2024 edition warnings

src/dc.rs
This would have been masked in release builds with wrapping arithmetic which is a worse outcome than just setting the prop delay to zero. 0 is closer to the real propagation delay than whatever enormous wrapped value was previously produced, so I think saturating is the least bad compared to wrapping.
Closes #302
=> Use saturating arithmetic when computing propagation delays

src/subdevice/mod.rs
I tested this by attempting to read from 0xffff:0 on a device that doesn't use that address.  It threw "0x06090011: Subindex does not exist" as expected.
=> Read the CoE abort code when there is an SDO abort

CHANGELOG.md, examples/sdo-info.rs, src/coe/mod.rs, src/coe/services.rs, src/error.rs, src/lib.rs, src/subdevice/mod.rs
To add this endpoint, I added two methods
(`SubDeviceRef::{sdo_info_object_description_list, sdo_info_object_quantities}`) and two types
(`crate::{ObjectDescriptionListType, ObjectDescriptionListTypeCounts}`) to the public interface.  I also made a modest change to the `MailboxError` type.
The application I have in mind for this feature is to list out the object dictionaries of every device on the bus to improve surveying, troubleshoot, and plain ol' hacking.  You can see the beginning of this in `/examples/sdo-info.rs`.  Some devices on the bus won't have the necessary mailboxes to support this kind of probing.  To handle that gracefully, the log messages that were produced at the same site as the `NoMailbox` errors needed to be lofted to where that error was actually problematic.  But …
=> Implement SDO Info Get Object Description List
