ethercrab-rs/ethercrab

- src/eeprom/mod.rs
- src/eeprom/reader.rs
- src/eeprom/types.rs
- src/slave/mod.rs
No user-facing changes. The EEPROM (SII) code should now be a bit easier to work on.
> Refactor EEPROM internals

- CHANGELOG.md
- src/dc.rs
- src/slave_group/configurator.rs
> Fix some arithmetic bugs and overflows

- .circleci/config.yml
- CHANGELOG.md
- TODO.md
- examples/akd.rs
- examples/dc.rs
- examples/ec400.rs
- examples/ek1100.rs
- examples/multiple-groups.rs
- src/client.rs
- src/eeprom/reader.rs
- src/error.rs
- src/lib.rs
- src/pdu_loop/frame_element/sendable_frame.rs
- src/pdu_loop/mod.rs
- src/pdu_loop/pdu_rx.rs
- src/pdu_loop/pdu_tx.rs
- src/pdu_loop/storage.rs
- src/slave/mod.rs
- src/slave_group/configurator.rs
- src/slave_group/mod.rs
- src/std.rs
> Add method to split PDU loop/TX/RX

- .circleci/config.yml
- Cargo.toml
- Justfile
- README.md
- README.tpl
- src/lib.rs
See individual commits for changes.
> Housekeeping

- Cargo.toml
- src/coe/mod.rs
- src/dl_status.rs
- src/mailbox.rs
- src/pdi.rs
- src/pdu_data.rs
- src/register.rs
Already found a couple of bugs. Nice.
> Add `heckcheck` fuzzer and a few tests

- src/dc.rs
This is a hopeful fix for https://github.com/ethercrab-rs/ethercrab/issues/63#issuecomment-1644821206
Again, I'm unable to test on my side because all my slave devices reported DC as supported which is weird. @jubeormk1 if you wouldn't mind giving this PR a test before I merge it that would be much appreciated!
```toml
ethercrab = { git = "https://github.com/ethercrab-rs/ethercrab.git", branch = "dont-read-non-dc-slaves" }
```
> Don't try to read RX times for non-DC slaves

- src/pdu_loop/mod.rs
The sent frame was being ignored by the receiving parser prior to this fix, so the test wasn't actually checking the whole round trip.
> Fix PDU roundtrip test to receive loopback

- Cargo.toml
- NOTES.md
- examples/jitter.rs
Idle curiosity lead me to make a basic jitter measurement using `hdrhistogram`. I could be recording it wrong and I'd like to add a chart GUI in the future but for now it prints some results every 1s after a 10s warmup time.
> Jitter measurements

- examples/embassy-stm32/Cargo.toml
As recommended by the Embassy devs
> Use patch.crates-io to include Embassy crates

- src/client.rs
- src/ds402.rs
- src/pdu_loop/frame_element/sendable_frame.rs
- src/pdu_loop/mod.rs
- src/pdu_loop/pdu_rx.rs
- src/pdu_loop/pdu_tx.rs
- src/register.rs
- src/slave/mod.rs
- src/slave/pdi.rs
- src/slave_group/mod.rs
- src/slave_state.rs
- src/std/linux/mod.rs
- tests/util.rs
Not perfect, but much nicer than before.
> Add a few more docs ready for a release

- CHANGELOG.md
- src/register.rs
Adds register entries for reading/writing watchdog parameters.
> Add registers for watchdog fields

- src/eeprom/mod.rs
Less efficient for single byte reads, but the code is easier to understand now, and consumes less space/memory. The single byte reads are only used by the `find_string` method so I think it's fine to be less efficient there.
> Remove internal 8 byte cache from EEPROM reader

- ethercrab-wire/src/impls.rs
- ethercrab-wire/tests/std.rs
> Support reading into `std::string::String`

- .circleci/config.yml
- ethercrab-wire-derive/Cargo.toml
- ethercrab-wire-derive/README.md
- ethercrab-wire-derive/benches/derive-enum.rs
- ethercrab-wire-derive/benches/derive-large.rs
- ethercrab-wire-derive/benches/derive-struct.rs
- ethercrab-wire-derive/src/generate_struct.rs
- ethercrab-wire-derive/src/lib.rs
- ethercrab-wire/README.md
- ethercrab-wire/src/lib.rs
- src/dl_status.rs
- src/register.rs
The docs aren't perfect but we can always add more.
> Add benchmarks and documentation for `EtherCrabWire*` traits

- src/coe/services.rs
- src/generate.rs
- src/mailbox.rs
I had some spare time to just have a play around.
> Small changes to reduce Embassy example binary size

- src/pdu_loop/pdu_flags.rs
- src/pdu_loop/pdu_header.rs
Internal only, small QoL improvement.
> A better name for "is not last" PDU flag

- NOTES.md
- src/command/mod.rs
- src/pdu_loop/frame_element/created_frame.rs
- src/pdu_loop/frame_element/receiving_frame.rs
- src/pdu_loop/pdu_header.rs
> Minor frame send performance improvement

- src/slave_group/mod.rs
Bit of a facepalm from me here. Fixes changes made in #191. Those were tested with other hardware which just happened to match the values.
> Fix PDI data length check

- CHANGELOG.md
- examples/ek1100.rs
- src/slave_group/mod.rs
> Add methods to transition out of OP back to INIT

- NOTES.md
- examples/dc.rs
- src/slave_group/mod.rs
This should probably be adapted to be SubDevice-scoped in the future as different SubDevices might want different SYNC1 configurations.
> Add basic group-level support for SYNC1

- src/client.rs
- src/command/reads.rs
- src/command/writes.rs
- src/pdu_loop/mod.rs
- src/slave_group/mod.rs
Also refactor some code so fixing one place fixes everywhere.
> Fix retry behaviour regression

- benches/pdu_loop.rs
- src/command/reads.rs
- src/command/writes.rs
- src/dc.rs
- src/pdu_loop/frame_box.rs
- src/pdu_loop/frame_element/created_frame.rs
- src/pdu_loop/frame_element/frame_box.rs
- src/pdu_loop/frame_element/mod.rs
- src/pdu_loop/frame_element/received_frame.rs
- src/pdu_loop/frame_element/receiving_frame.rs
- src/pdu_loop/frame_element/sendable_frame.rs
- src/pdu_loop/mod.rs
- src/pdu_loop/pdu_header.rs
- src/pdu_loop/pdu_rx.rs
- src/pdu_loop/pdu_tx.rs
- src/pdu_loop/storage.rs
- src/slave_group/mod.rs
- tests/replay-ek1914-el3004-mailbox.rs
- tests/replay-ek1914-no-complete-access.rs
This is all internal work, but makes the API cleaner to use, and encapsulates some of the `unsafe` stuff in a smaller set of files, hopefully make it a bit easier to understand and audit.
> Refactor PDU loop internals

- CHANGELOG.md
- src/lib.rs
> Publicly expose `DcSupport` enum

- src/client.rs
- src/client_config.rs
- src/command/mod.rs
- src/command/reads.rs
- src/command/writes.rs
- src/pdu_loop/frame_element/created_frame.rs
- src/slave_group/mod.rs
Yet more...
`master`:
```
92208     112   57288  149608   24868 ethercrab-stm32-embassy
```
This PR:
```
89768     112   57288  147168   23ee0 ethercrab-stm32-embassy
```
> Binary size improvements

- CHANGELOG.md
- Cargo.toml
- examples/windows.rs
- rust-toolchain.toml
- src/lib.rs
- src/pdu_loop/mod.rs
- src/pdu_loop/pdu_rx.rs
- src/std/io_uring.rs
- src/std/mod.rs
- src/std/unix/mod.rs
- src/std/windows.rs
- tests/util.rs
> Backport #246 to v0.5

- .circleci/config.yml
- CHANGELOG.md
- Cargo.toml
- src/error.rs
- src/pdu_loop/frame_element/receiving_frame.rs
- src/pdu_loop/mod.rs
- src/std/io_uring.rs
- src/std/unix/mod.rs
- src/std/windows.rs
~This _may_ help or fix #259~
This fixes #259 :grin: (as tested in that issue)
> Handle cases where a frame is received before its future is registered

- .circleci/config.yml
- CHANGELOG.md
- Cargo.toml
- src/error.rs
- src/pdu_loop/frame_element/receiving_frame.rs
- src/pdu_loop/mod.rs
- src/std/io_uring.rs
- src/std/unix/mod.rs
- src/std/windows.rs
> Backport #260 to 0.5.x

- CHANGELOG.md
- src/error.rs
- src/subdevice/mod.rs
Please see #274 for all details. This PR is to hopefully fix the weird refusal to enable merging in Github's UI.
> Reading SDO Arrays (GH-fixed copy of #274)

- CHANGELOG.md
- src/eeprom/types.rs
- src/subdevice/configuration.rs
> Backport #294 to 0.5.x

- src/coe/services.rs
- src/error.rs
- src/subdevice/mod.rs
See #236, although modified to remove unused error type.
> Backport #236 to 0.5.x

- CHANGELOG.md
- src/coe/services.rs
- src/subdevice/mod.rs
See discussion [here](https://github.com/ethercrab-rs/ethercrab/pull/236#issuecomment-2767199552). I had misunderstood the spec.
> Remove mailbox counter check and warning

- src/dc.rs
- src/subdevice/ports.rs
Use `let else`, add some comments, reduce stack size slightly by reassigning a variable, add clippy checks to make some time calculations a bit more robust.
> Minor cleanup in `dc.rs`

- src/subdevice/configuration.rs
> Only iterate through as many SMs as we have info for

- src/std/io_uring.rs
This registers a probe to check if read/write opcodes are supported before starting the tx/rx loop on debug builds, making it   panic instead of giving EINVAL on older kernels
> check for io_uring opcode support in debug builds
